### ISSUE TITLE
memory经典回忆

### ISSUE THREAD

**Issue by Echo-Fish-2** [czhlin/cpc100#1]
音乐播放功能无法实现

**Comment by Echo-Fish-2** [comment]
能帮忙看一下是哪里出现问题了吗？

**Comment by czhlin** [comment]
> 音乐播放功能无法实现
我这边能进行播放哇

**Comment by czhlin** [comment]
> 音乐播放功能无法实现

我这边能进行播放哇

**Comment by Echo-Fish-2** [comment]
整个项目都和github上一样的嘛？如果可以的话，能把你电脑上的项目打包发给我看看嘛？我这边音乐播放功能就是一片空白，只有视频可以播放▶️ 。拜托拜托🙏🏻 谢谢啦！
---原始邮件---
***@***.***&gt;
发送时间:2021年6月10日 星期四 上午8:48
***@***.***&gt;
***@***.******@***.***&gt;
主题:Re: [czhlin/cpc100] memory经典回忆 (#1)



音乐播放功能无法实现

我这边能进行播放哇

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by czhlin** [comment]
> 整个项目都和github上一样的嘛？如果可以的话，能把你电脑上的项目打包发给我看看嘛？我这边音乐播放功能就是一片空白，只有视频可以播放▶️ 。拜托拜托🙏🏻 谢谢啦！ ---原始邮件--- ***@***.***&gt; 发送时间:2021年6月10日 星期四 上午8:48 ***@***.***&gt; ***@***.******@***.***&gt; 主题:Re: [czhlin/cpc100] memory经典回忆 (#1) 音乐播放功能无法实现 我这边能进行播放哇 &mdash; You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread. Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

qq:2324133088
